base_url: https://test.bike.ledear.cn
header:
  content-type: application/json
  source_type: '3'
  area_id: '10'
login_header:
  content-type: application/json
  source_type: '3'
log_level: INFO
handler_log_log_level: INFO
all_api_yaml: /web_testcase/case/all_api.yaml