# 乐迪共享测试域名
#base_url: https://test.bike.ledear.cn
# 乐迪长租测试域名
#base_url: https://test.rent.ledear.cn
#base_url: https://dev.rent.ledear.cn:28000
base_url: https://test.rent.ledear.cn
header:
  admin:
    content-type: application/json
    source_type: '3'
  factory_wx_mini:
    content-type: application/json
    source_type: '4'
  user_wx_mini:
    content-type: application/json
    source_type: '7'
#  area_id: '10'
login_header:
  admin:
    content-type: application/json
    source_type: '3'
  factory_wx_mini:
    content-type: application/json
    source_type: '4'
  user_wx_mini:
    content-type: application/json
    source_type: '7'
log_level: INFO
handler_log_log_level: INFO
all_api_yaml: /all_testcase/case/all_api.yaml


# 数据库连接
mysql_host: ledear-test-porladb.rwlb.rds.aliyuncs.com
#mysql_host: 192.168.0.7
#host: 162.14.82.120
mysql_port: 3306
#mysql_port: 3308
mysql_user: dba
#mysql_user: root
#user: root
mysql_password: XQiVFQyXLZ^iUWeA
#mysql_password: iupward.123
#password: 123456
mysql_db: rent
#db: bookshop
mysql_charset: utf8


# redis连接
redis_host: ledear-test-redis.redis.rds.aliyuncs.com
redis_port: 36379
redis_db: 1
redis_password: iupward@123
